import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LogProvider } from "../contexts/LogContext";
import LogModal from "../components/LogModal";
import LogToggle from "../components/LogToggle";
import ConnectionMonitor from "../components/ConnectionMonitor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LogProvider>
          {children}
          <LogModal />
          <LogToggle />
          <ConnectionMonitor />
        </LogProvider>
      </body>
    </html>
  );
}
